name: Admin-Frontend-CI_DEV

on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: |
          docker build -t ${{ secrets.IMAGE_TAG_DEV }} -t ${{ secrets.IMAGE_TAG_DEV }}:${{ github.sha }} .

      - name: Docker login
        run: |
          docker login -u ${{ secrets.REGISTRY_USER_DEV }} -p ${{ secrets.REGISTRY_PASS_DEV }}

      - name: Docker push
        run: |
          docker push ${{ secrets.IMAGE_TAG_DEV }}:latest
          docker push ${{ secrets.IMAGE_TAG_DEV }}:${{ github.sha }}

      - name: Docker logout
        run: |
          docker logout
